apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ../base

patches:
- patch: |-
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: local-path-config
      namespace: local-path-storage
    data:
      config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/var/mnt/extra"]
                }
                ]
        }   
        setup: |-
              #!/bin/sh
              set -eu
              mkdir -m 0777 -p "$VOL_DIR"
        teardown: |-
              #!/bin/sh
              set -eu
              rm -rf "$VOL_DIR"
        helperPod.yaml: |-
              apiVersion: v1
              kind: Pod
              metadata:
                name: helper-pod
              spec:
                priorityClassName: system-node-critical
                tolerations:
                  - key: node.kubernetes.io/disk-pressure
                    operator: Exists
                    effect: NoSchedule
                containers:
                - name: helper-pod 
- patch: |-
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: local-path
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"    
- patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: local-path-storage
      labels:
        pod-security.kubernetes.io/enforce: privileged    
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: local-path-provisioner
      namespace: local-path-storage
    spec:
      template:
        spec:
          nodeSelector:
            extraDiskNode: "true"
