apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ../base

patches:
- patch: |-
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: local-path-config
      namespace: local-path-provisioner
    data:
      config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/var/mnt/extra"]
                }
                ]
        }    
- patch: |-
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: local-path
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"    
- patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: local-path-provisioner
      labels:
        pod-security.kubernetes.io/enforce: privileged    
- patch: |-
    apiVersion: v1
    kind: Deployment
    metadata:
      name: local-path-provisioner
    spec:
      template:
        spec:
          nodeSelector:
            extraDiskNode: "true"
