{
 "title": "Trivy Operator",
 "tags": [
  "trivy",
  "security",
  "vulnerabilities"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Critical CVEs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\"})"
    }
   ]
  },
  {
   "title": "High CVEs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\"})"
    }
   ]
  },
  {
   "title": "Critical Config Findings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"Critical\"})"
    }
   ]
  },
  {
   "title": "High Config Findings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"High\"})"
    }
   ]
  },
  { "title": "Actionable Findings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Top Workloads by CVEs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sum(trivy_image_vulnerabilities{severity=~\"Critical|High\"}) by (namespace, resource_name))",
     "legendFormat": "{{namespace}}/{{resource_name}}"
    }
   ]
  },
  {
   "title": "Top Namespaces by CVEs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "topk(10, sum(trivy_image_vulnerabilities{severity=~\"Critical|High\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Top Workloads by Config Findings",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "topk(10, sum(trivy_resource_configaudits{severity=~\"Critical|High\"}) by (namespace, resource_name))",
     "legendFormat": "{{namespace}}/{{resource_name}}"
    }
   ]
  }
 ]
}