apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-gitea-cnpg-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: gitea-cnpg-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: gitea
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: GITEA_POSTGRES_PASSWORD
