apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-gitea-postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: gitea-postgresql
  data:
    - secretKey: password
      remoteRef:
        key: GITEA_POSTGRES_PASSWORD
    - secretKey: postgres-password
      remoteRef:
        key: GITEA_POSTGRES_ADMIN_PASSWORD
