apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./external-secret.yaml
  - ./external-secret-postgresql.yaml
  - ./httproute-public.yaml
  - ./cilium-network-policy.yaml
  - ./pvc-shared-storage-nas.yaml
