---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.yiannis.io
  admin.enabled: "false"
  dex.config: |
    connectors:
    - config:
        issuer: http://authz.yiannis.io/application/o/argocd/
        clientID: qXAitOkMZQKx4rpAxHcHroIX3Wdn4phUjO6sj9if
        clientSecret: $dex.authentik.clientSecret
        insecureEnableGroups: true
        scopes:
          - openid
          - profile
          - email
      name: authentik
      type: oidc
      id: authentik