---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
  #dexserver.disable.tls: "true"
  #server.dex.server.plaintext: "true"
  otlp.address: "otel-collector-opentelemetry-collector:4317"