---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.yiannis.io
  dex.config: |
    connectors:
    - config:
        issuer: http://authentik.yiannis.io/application/o/argocd/
        clientID: 4RrCJ2nUrF7t8yxGdKDBe2s9Dxh64jsYFeMEs5Am
        clientSecret: $dex.authentik.clientSecret
        insecureEnableGroups: true
        scopes:
          - openid
          - profile
          - email
      name: authentik
      type: oidc
      id: authentik