---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      hostAliases:
      - ip: 192.168.1.7
        hostnames:
        - "authentik.yiannis.io"
        - "gitea.yiannis.io"
