apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-authentik-secret-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: authentik-secret-key
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: AUTHENTIK_SECRET_KEY