apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: auth-api
  data:
    - secretKey: authentik-postgres-password
      remoteRef:
        key: AUTHENTIK_POSTGRES_PASSWORD