apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: authentik-postgres-password
  data:
    - secretKey: authentik/AUTHENTIK_POSTGRES_PASSWORD
      remoteRef:
        key: authentik/AUTHENTIK_POSTGRES_PASSWORD