apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik-private
  namespace: authentik
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Authentik
    gethomepage.dev/href: "https://authentik.yiannis.io"
    gethomepage.dev/group: Platform
    gethomepage.dev/icon: authentik.png
    gethomepage.dev/name: authentik
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/widget.type: "authentik"
    gethomepage.dev/widget.version: "2"
    gethomepage.dev/widget.url: "http://authentik-server.authentik.svc.cluster.local"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_AUTHENTIK}}"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: private
    namespace: traefik
    sectionName: websecure-authentik
  hostnames:
  - authentik.yiannis.io
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ""
      kind: Service
      name: authentik-server
      port: 80
      weight: 1
