apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authentik-server-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik
      app.kubernetes.io/component: server
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: traefik
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: homepage
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: authentik
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authentik-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/instance: authentik
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: authentik
    ports:
    - protocol: TCP
      port: 1
      endPort: 65535
    - protocol: UDP
      port: 1
      endPort: 65535
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: authentik
      podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
          cnpg.io/cluster: authentik-database
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
