apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-test
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: test
  data:
    - secretKey: TEST
      remoteRef:
        key: /TEST