global:  
  hostAliases:
    - ip: 192.168.1.7
      hostnames:
      - "argocd.yiannis.io"
      - "authentik.yiannis.io"

  nodeSelector:
    extraDiskNode: "true"
    kubernetes.io/hostname: k8s-node-4

authentik:
  secret_key: "PleaseGenerateA50CharKey"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: false
  postgresql:
    password: "ThisIsNotASecurePassword"
  log_level: "info"

server:
  ingress:
    # Specify kubernetes ingress controller class name
    ingressClassName: traefik
    enabled: true
    hosts:
      # Specify external host name
      - authentik.yiannis.io

postgresql:
  enabled: true
  postgresqlPassword: "ThisIsNotASecurePassword"
  nodeSelector:
    extraDiskNode: "true"
    kubernetes.io/hostname: k8s-node-4
redis:
  enabled: true
  nodeSelector:
    extraDiskNode: "true"
    kubernetes.io/hostname: k8s-node-4