global:  
  nodeSelector:
    extraDiskNode: "true"
    kubernetes.io/hostname: k8s-node-4

authentik:
  secret_key: "PleaseGenerateA50CharKey"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: false
  postgresql:
    host: authentik-database-rw.authentik.svc.cluster.local
    name: authentik
    user: authentik
    password: file:///postgres-creds/AUTHENTIK_POSTGRES_PASSWORD
  log_level: "info"

server:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
  ingress:
    # Specify kubernetes ingress controller class name
    ingressClassName: traefik
    enabled: true
    hosts:
      # Specify external host name
      - authentik.yiannis.io
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Authentik
      gethomepage.dev/href: "https://authentik.yiannis.io"
      gethomepage.dev/group: Platform
      gethomepage.dev/icon: authentik.png
      gethomepage.dev/name: authentik
      gethomepage.dev/pod-selector: ""
      gethomepage.dev/widget.type: "authentik"
      gethomepage.dev/widget.url: "http://authentik-server.authentik.svc.cluster.local"
      gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_AUTHENTIK}}"
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-postgres-credentials
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
  envFrom:
  - secretRef:
      name: authentik-secret-key

postgresql:
  enabled: false
  image:
    tag: 15
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r50
      pullPolicy: IfNotPresent
  auth:
    existingSecret: authentik-postgres-credentials
    secretKeys:
      adminPasswordKey: AUTHENTIK_POSTGRES_ADMIN_PASSWORD
      userPasswordKey: AUTHENTIK_POSTGRES_PASSWORD
  primary:
    nodeSelector:
      extraDiskNode: "true"

redis:
  enabled: true
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r50
      pullPolicy: IfNotPresent
  master:
    nodeSelector:
      extraDiskNode: "true"

worker:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-postgres-credentials
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
  envFrom:
  - secretRef:
      name: authentik-secret-key
