authentik:
  secret_key: "PleaseGenerateA50CharKey"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: false
  postgresql:
    password: "ThisIsNotASecurePassword"

ingress:
  # Specify kubernetes ingress controller class name
  ingressClassName: traefik
  enabled: true
  hosts:
    # Specify external host name
    - host: authentik.yiannis.io
      paths:
        - path: "/"
          pathType: Prefix

postgresql:
  enabled: false
  postgresqlPassword: "ThisIsNotASecurePassword"
redis:
  enabled: false