operator:
  unmanagedPodWatcher:
    restart: true

routingMode: tunnel
tunnelProtocol: vxlan
tunnelPort: 8473

cni:
  customConf: false
  uninstall: false

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.245.0.0/16

kubeProxyReplacement: false
policyEnforcementMode: default

bpf:
  hostLegacyRouting: true

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true
      trustCRDsExist: true
    dashboards:
      enabled: true
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/Hubble
  relay:
    enabled: true
  ui:
    enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
  dashboards:
    enabled: true
    annotations:
      k8s-sidecar-target-directory: /tmp/dashboards/Cilium

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      trustCRDsExist: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
