apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-paperless-consume
provisioner: nfs.csi.k8s.io
allowVolumeExpansion: true
parameters:
  server: 192.168.88.110
  share: /mnt/DataPool/k8s/paperless-consume
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
