# Configure options applied to all pods
defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  # Configure the main controller
  qbittorrent:

    # Configure the pod-specific securityContext
    pod:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30

    containers:
      # Configure the main application container
      qbittorrent:
        image:
          # -- image repository
          repository: reg.yiannis.io/proxy-dockerhub/linuxserver/qbittorrent
          # -- pinned to latest stable release tag: 5.1.4-r3-ls453
          digest: sha256:c9990949e968e99333f47f49da7d16e81ba6e1469c8c46807a65b984c9e8b6ff
        # Configure the container-specific securityContext
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - SETGID
              - SETUID
        resources:
          requests:
          #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
          #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
          #   gpu.intel.com/i915: 1
            cpu: 200m
            memory: 2048Mi
          limits:
          #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
          #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
          #  gpu.intel.com/i915: 1
            memory: 2048Mi


service:
  # Configure a service for the main application
  controller: qbittorrent
  qbittorrent:
    type: ClusterIP
    ports:
      http:
        port: 8080

ingress:
  # Configure an Ingress for the main application
  qbittorrent:
    enabled: false
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: QBittorrent
      gethomepage.dev/href: "https://qb.yiannis.io"
      gethomepage.dev/group: Media
      gethomepage.dev/icon: qbittorrent.png
      gethomepage.dev/name: qbittorrent
      gethomepage.dev/pod-selector: ""
      gethomepage.dev/widget.type: "qbittorrent"
      gethomepage.dev/widget.url: "http://qbittorrent.media-video.svc.cluster.local:8080"
      gethomepage.dev/widget.username: '{{`{{HOMEPAGE_VAR_QBITTORRENT_USER}}`}}'
      gethomepage.dev/widget.password: '{{`{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}`}}'
      #gethomepage.dev/weight: "10" # optional
      #gethomepage.dev/instance: "public" # optional
      traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
    ingressClassName: "traefik"
    hosts:
      - host: "qb.yiannis.io"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: qbittorrent
              port: http

persistence:
  # Configure the main configuration storage location
  # config:
  #   enabled: true
  #   type: persistentVolumeClaim
  #   storageClass: truenas-video
  #   accessMode: ReadWriteMany
  #   server: 192.168.88.10
  #   path: /media/jellyfin
  #   advancedMounts:
  #     main:
  #       main:
  #         - path: /config
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: truenas-apps
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config

  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: media-video
    globalMounts:
      - path: /downloads
