apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps/argocd/applications/argocd-self.yaml
  - apps/metallb/applications/metallb.yaml
  - apps/authentik/applications/authentik.yaml
  - apps/authentik/applications/authentik-db.yaml
  - apps/csi-driver-nfs/applications/csi-driver-nfs.yaml
  - apps/crowdsec/applications/crowdsec.yaml
  - apps/kyverno/applications/kyverno.yaml
  - apps/kyverno/applications/kyverno-policies.yaml
  - apps/reflector/applications/reflector.yaml
  #- apps/cloudflare/applications/cloudflare.yaml
  #- apps/falco/applications/falco.yaml
  - apps/external-secrets/applications/external-secrets.yaml
  - apps/vertical-pod-autoscaler/applications/vertical-pod-autoscaler.yaml
  - apps/cilium/applications/cilium.yaml
  - apps/trivy-operator/applications/trivy-operator.yaml
  - apps/local-storage-provisioner/applications/local-storage-provisioner.yaml
  - apps/cloudnative-pg/applications/cloudnative-pg.yaml
  - apps/alloy/applications/alloy.yaml
  - apps/qbittorrent/applications/qbittorrent.yaml
  - apps/jellyfin/applications/jellyfin.yaml
  - apps/prowlarr/applications/prowlarr.yaml
  - apps/sonarr/applications/sonarr.yaml
  - apps/radarr/applications/radarr.yaml
  - apps/jellyseerr/applications/jellyseerr.yaml
  - apps/immich/applications/immich-db.yaml
  - apps/immich/applications/immich.yaml
  - apps/flaresolverr/applications/flaresolverr.yaml
  - apps/gitea/applications/gitea-db.yaml
  - apps/gitea/applications/gitea.yaml
  - apps/traefik/applications/traefik.yaml
  - apps/cert-manager/applications/cert-manager.yaml
  - apps/kube-prometheus-stack/applications/kube-prometheus-stack.yaml
  - apps/loki/applications/loki.yaml
  #- apps/tempo/applications/tempo.yaml
  - apps/homepage/applications/homepage.yaml
  - apps/tailscale/applications/tailscale.yaml
  #- apps/firefly-iii/applications/firefly-iii.yaml
  #- apps/loki-stack/applications/loki-stack.yaml
  - apps/paperless-ngx/applications/paperless-ngx-db.yaml
  - apps/paperless-ngx/applications/paperless-ngx.yaml
