apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  labels:
    app: cloudnative-pg
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.28.0
    helm:
      releaseName: cnpg
      valueFiles:
      - $values/apps/cloudnative-pg/values/values.yaml
  - repoURL: https://github.com/ipanagiotidis/homelab-gitops.git
    targetRevision: master
    ref: values
  - repoURL: https://github.com/ipanagiotidis/homelab-gitops.git
    path: apps/cloudnative-pg/kustomization
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        security.yiannis.io/require-harbor: "true"
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - ServerSideApply=true
