apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-cloudflare-api-key-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-api-key-secret
    creationPolicy: Merge
  data:
    - secretKey: api-key
      remoteRef:
        key: CLOUDFLARE_API_KEY