image:
  repository: ghcr.io/gethomepage/homepage
  tag: latest

# Enable RBAC. RBAC is necessary to use Kubernetes integration
enableRbac: true

extraClusterRoles:
  # - apiGroups:
  #   - some-group
  #   resources:
  #   - some-resource
  #   verbs:
  #   - get

serviceAccount:
  # Specify a different service account name. When blank it will default to the release
  # name if *create* is enabled, otherwise it will refer to the default service account.
  name: ""
  # Create service account. Needed when RBAC is enabled.
  create: true

service:
  main:
    ports:
      http:
        port: 3000

controller:
  strategy: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

# Enable the ingress to expose Homepage to the network.
ingress:
  main:
    enabled: true
    labels:
      # This label will enable discover of this deployment in Homepage
      gethomepage.dev/enabled: "true"
    annotations:
      # These annotations will configure how this deployment is shown in Homepage
      gethomepage.dev/name: "Homepage"
      gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
      gethomepage.dev/group: "A New Group"
      gethomepage.dev/icon: "homepage.png"
      #traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
    ingressClassName: "traefik"
    hosts:
      - host: &host "home.yiannis.io"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - *host

# All the config files for Homepage can be specified under their relevant config block.
config:
  # To use an existing ConfigMap uncomment this line and specify the name
  # useExistingConfigMap: existing-homepage-configmap
  bookmarks: []
  services:
    - Infrastructure:
      - adguard:
          description: Adguard
          href: "{{HOMEPAGE_VAR_ADGUARD_SERVER}}"
          icon: adguard-home.png
          name: adguard
          widget:
            type: "adguard"
            url: "{{HOMEPAGE_VAR_ADGUARD_SERVER}}"
            username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
            password: "{{HOMEPAGE_VAR_ADGUARD}}"
    # - Monitoring:
    #   - grafana:
    #       description: Grafana
    #       href: "https://gfn.yiannis.io"
    #       icon: grafana.png
    #       name: grafana
    #       widgets:
    #         - type: "grafana"
    #           url: https://gfn.yiannis.io
    #           username: sa-1-homepage-sa-ba09bf3c-d8e1-4e3e-90a6-f21f7b9513bf
    #           password: "{{HOMEPAGE_VAR_GRAFANA}}"
    # - Security:
    #   - crowdsec:
    #       description: Crowdsec
    #       href: "https://crowdsec-service.crowdsec.svc.cluster.local:8080"
    #       icon: crowdsec.png
    #       name: crowdsec
    #       widgets:
    #         - type: crowdsec
    #           url: https://crowdsec-service.crowdsec.svc.cluster.local:8080
  widgets:
    # Uncomment to enable Kubernetes integration
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "k8s-homelab"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  kubernetes:
    # change mode to 'cluster' to use RBAC service account
    mode: cluster
    ingress: true
    traefik: true
  # docker:
  # settings:
  #   ingress: true
  #   traefik: true

# -- Main environment variables. Template enabled.
# Syntax options:
# A) TZ: UTC
# B) PASSWD: '{{ .Release.Name }}'
# C) PASSWD:
#      configMapKeyRef:
#        name: config-map-name
#        key: key-name
# D) PASSWD:
#      valueFrom:
#        secretKeyRef:
#          name: secret-name
#          key: key-name
#      ...
# E) - name: TZ
#      value: UTC
# F) - name: TZ
#      value: '{{ .Release.Name }}'
env:
  HOMEPAGE_ALLOWED_HOSTS: home.yiannis.io
  HOMEPAGE_VAR_ARGOCD_READONLY:
    valueFrom:
      secretKeyRef:
        name: homepage-secrets
        key: argocd-key
  HOMEPAGE_VAR_AUTHENTIK:
    valueFrom:
      secretKeyRef:
        name: homepage-secrets
        key: authentik-key
  HOMEPAGE_VAR_GITEA:
    valueFrom:
      secretKeyRef:
        name: homepage-secrets
        key: gitea-key
  HOMEPAGE_VAR_GRAFANA:
    valueFrom:
      secretKeyRef:
        name: homepage-secrets
        key: grafana-key
  HOMEPAGE_VAR_ADGUARD:
    valueFrom:
      secretKeyRef:
        name: homepage-secrets
        key: adguard-key
  HOMEPAGE_VAR_ADGUARD_SERVER:
    valueFrom:
      secretKeyRef:
        name: homepage-secrets
        key: adguard-server
  HOMEPAGE_VAR_ADGUARD_USER:
    valueFrom:
      secretKeyRef:
        name: homepage-secrets
        key: adguard-user

# To include environment variables from other configs or other secrets for use in
# Homepage's variable substitutions. Refer to them here.
# envFrom:
#   - secretRef:
#       name: my-secret
#   - configMapRef:
#       name: my-configmap

persistence:
  logs:
    enabled: true
    type: emptyDir
    mountPath: /app/config/logs


resources:
  requests:
    memory: 10Mi
    cpu: 10m
  limits:
    memory: 200Mi
    cpu: 500m

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

podSecurityContext:
  runAsNonRoot: true
  fsGroupChangePolicy: "OnRootMismatch"
  runAsUser: 1000
  fsGroup: 1000