apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  labels:
    app: cilium
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.19.2
    helm:
      releaseName: cilium
      valueFiles:
        - $values/apps/cilium/values/values.yaml
  - repoURL: https://github.com/ipanagiotidis/homelab-gitops.git
    targetRevision: master
    ref: values
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - ServerSideApply=true
