# Configure options applied to all pods
defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  # Configure the main controller
  flaresolverr:

    # Configure the pod-specific securityContext
    pod:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault

    containers:
      # Configure the main application container
      flaresolverr:
        image:
          # -- image repository
          repository: reg.yiannis.io/proxy-dockerhub/flaresolverr/flaresolverr
          # -- pinned to latest stable release tag: v3.4.6
          digest: sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
        # Configure the container-specific securityContext
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        # -- Configure the resource requests and/or limits for the Pod
        resources:
          requests:
          #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
          #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
          #   gpu.intel.com/i915: 1
            cpu: 10m
            memory: 64Mi
          limits:
          #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
          #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
          #  gpu.intel.com/i915: 1
            memory: 4096Mi


service:
  # Configure a service for the main application
  controller: flaresolverr
  flaresolverr:
    type: ClusterIP
    ports:
      http:
        port: 8191
