apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-adguard-exporter
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: adguard-exporter-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: ADGUARD_SERVERS
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HOMEPAGE_VAR_ADGUARD_SERVER
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: ADGUARD_USERNAMES
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HOMEPAGE_VAR_ADGUARD_USER
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: ADGUARD_PASSWORDS
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HOMEPAGE_VAR_ADGUARD
      metadataPolicy: None
      nullBytePolicy: Ignore
