apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: adguard-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adguard-exporter
    spec:
      containers:
        - name: adguard-exporter
          image: ghcr.io/henrywhitaker3/adguard-exporter:v1.2.1@sha256:42a9581bae4a91e6d4985415d1fe89ab9b1f50fbe2945a1c122d212d6354b747
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9618
          env:
            - name: ADGUARD_SERVERS
              valueFrom:
                secretKeyRef:
                  name: adguard-exporter-secret
                  key: ADGUARD_SERVERS
            - name: ADGUARD_USERNAMES
              valueFrom:
                secretKeyRef:
                  name: adguard-exporter-secret
                  key: ADGUARD_USERNAMES
            - name: ADGUARD_PASSWORDS
              valueFrom:
                secretKeyRef:
                  name: adguard-exporter-secret
                  key: ADGUARD_PASSWORDS
            - name: INTERVAL
              value: 30s
            - name: BIND_ADDR
              value: :9618
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
      securityContext:
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: adguard-exporter
spec:
  selector:
    app.kubernetes.io/name: adguard-exporter
  ports:
    - name: metrics
      port: 9618
      targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adguard-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: adguard-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: adguard-exporter
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: adguard-exporter
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 9618
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.88.246/32
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 3000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
