apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-adguard-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: adguard-exporter-secret
  data:
    - secretKey: ADGUARD_SERVERS
      remoteRef:
        key: HOMEPAGE_VAR_ADGUARD_SERVER
    - secretKey: ADGUARD_USERNAMES
      remoteRef:
        key: HOMEPAGE_VAR_ADGUARD_USER
    - secretKey: ADGUARD_PASSWORDS
      remoteRef:
        key: HOMEPAGE_VAR_ADGUARD
