apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-grafana-client
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-client
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      nullBytePolicy: Ignore
      path: GRAFANA_CLIENT_
