apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-grafana-client
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-client
  dataFrom:
    - find:
        path: GRAFANA_CLIENT_