apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./external-secret.yaml
  - ./argocd-servicemonitors.yaml
  - ./adguard-external-secret.yaml
  - ./adguard-exporter.yaml
  - ./adguard-exporter-cilium-network-policy.yaml
  - ./httproute-grafana-private.yaml
  - ./cilium-network-policy.yaml
  - ./dashboards
