apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-tailscale-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: tailscale-auth
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: TAILSCALE