crds:
  migration:
    image:
      registry: reg.yiannis.io
      defaultRegistry: reg.yiannis.io
      repository: proxy-kyverno/kyverno/kyverno-cli
      tag: v1.18.0@sha256:1e99a199adb36cedddf5c3e2fc24a150e26cf2e18b9e8dfe505a3c862647a4eb

config:
  webhooks:
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - kube-system
        - kyverno

  resourceFiltersExcludeNamespaces:
  - kyverno

features:
  policyReports:
    enabled: true
  backgroundScan:
    enabled: true
    backgroundScanInterval: 1h

test:
  image:
    registry: reg.yiannis.io
    repository: proxy-ghcr/kyverno/readiness-checker
    tag: v0.1.0@sha256:c54c0aa24d536f7a31ed854db4f2b2d6863b41d7d85725e21f80cd318c4e815b # v0.1.0

webhooksCleanup:
  image:
    registry: reg.yiannis.io
    repository: proxy-k8s/kubectl
    tag: v1.34.3@sha256:1c6309bd167feb49b2bc1605bce05973002872fd0d26a2e76499ed0c903ea3cf # v1.34.3

admissionController:
  initContainer:
    image:
      registry: reg.yiannis.io
      repository: proxy-kyverno/kyverno/kyvernopre
      tag: v1.18.0@sha256:60b53ebf646f788e6e5d312f9cbf267d7537ec14afec68bde2e1dad55c552cc7 # v1.18.0
  container:
    image:
      registry: reg.yiannis.io
      repository: proxy-kyverno/kyverno/kyverno
      tag: v1.18.0@sha256:cb033c200dc85be0a4d38e1a72894038a0c067d73f1ce6aedd569f9769a3d262 # v1.18.0
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 1m

backgroundController:
  image:
    registry: reg.yiannis.io
    repository: proxy-kyverno/kyverno/background-controller
    tag: v1.18.0@sha256:fd6d30964297f1c94c2d741a1c44d055994cd4354e6f7e718cad59e6b5aa6c66 # v1.18.0
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 1m

cleanupController:
  image:
    registry: reg.yiannis.io
    repository: proxy-kyverno/kyverno/cleanup-controller
    tag: v1.18.0@sha256:a2a060b731f1ea54de2295b886c600d65af032fec18096a816424acfe8dec7d2 # v1.18.0
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 1m

reportsController:
  image:
    registry: reg.yiannis.io
    repository: proxy-kyverno/kyverno/reports-controller
    tag: v1.18.0@sha256:0090bf10eabae091ceb48c38fb894580b63c4e76e40137b7972f5895f0402110 # v1.18.0
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 1m
