crds:
  migration:
    image:
      registry: reg.yiannis.io
      defaultRegistry: reg.yiannis.io
      repository: proxy-kyverno/kyverno/kyverno-cli
      tag: v1.18.2@sha256:7224ed05508c24419c3df98114c28ba682ad0a940dcdb7b9fdba0a4b6bf943cf

config:
  webhooks:
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - kube-system
        - kyverno

  resourceFiltersExcludeNamespaces:
  - kyverno

features:
  policyReports:
    enabled: true
  backgroundScan:
    enabled: true
    backgroundScanInterval: 1h

test:
  image:
    registry: reg.yiannis.io
    repository: proxy-ghcr/kyverno/readiness-checker
    tag: v0.1.0@sha256:c54c0aa24d536f7a31ed854db4f2b2d6863b41d7d85725e21f80cd318c4e815b # v0.1.0

webhooksCleanup:
  image:
    registry: reg.yiannis.io
    repository: proxy-k8s/kubectl
    tag: v1.34.3@sha256:1c6309bd167feb49b2bc1605bce05973002872fd0d26a2e76499ed0c903ea3cf # v1.34.3

admissionController:
  initContainer:
    image:
      registry: reg.yiannis.io
      repository: proxy-kyverno/kyverno/kyvernopre
      tag: v1.18.2@sha256:cd8cb4a31d25b3992734fb8f24a90ef691c90ce49338c89bea96792160eacb98 # v1.18.2
  container:
    image:
      registry: reg.yiannis.io
      repository: proxy-kyverno/kyverno/kyverno
      tag: v1.18.2@sha256:0a540e2ddf74d0d2d3d45f9ef248d7dbc96576accdbcc6a2dd7eaff9fea56504 # v1.18.2
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 1m

backgroundController:
  image:
    registry: reg.yiannis.io
    repository: proxy-kyverno/kyverno/background-controller
    tag: v1.18.2@sha256:d62566ce41bd0d4a32bf2cf44b9ebfc02c36374f821f83070890287f62f68671 # v1.18.2
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 1m

cleanupController:
  image:
    registry: reg.yiannis.io
    repository: proxy-kyverno/kyverno/cleanup-controller
    tag: v1.18.2@sha256:b0395d29ae332276e6910eb40418be9bc127c068d659f90aa1bcddd6be99ccb4 # v1.18.2
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 1m

reportsController:
  image:
    registry: reg.yiannis.io
    repository: proxy-kyverno/kyverno/reports-controller
    tag: v1.18.2@sha256:f09cf305170014e191b94e1c54f5be73163d8824eefad49349675c4efe43159a # v1.18.2
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 1m
