apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-speedtest-tracker
  namespace: speedtest
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: speedtest-tracker-secret
  data:
    - secretKey: app-key
      remoteRef:
        key: SPEEDTEST_TRACKER_APP_KEY
