apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-gitea-authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-cloudflare-tunnel-remote
  data:
    - secretKey: tunnelToken
      remoteRef:
        key: CLOUDFLARE_TOKEN_1