apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-cloudflare-tunnel-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: tunnel-token
  data:
    - secretKey: token
      remoteRef:
        key: CLOUDFLARE_TOKEN_1
