apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: crowdsec-lapi
  namespace: crowdsec
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crowdsec-lapi
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
