apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kyverno-admission-controller
  namespace: kyverno
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kyverno-admission-controller
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kyverno-background-controller
  namespace: kyverno
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kyverno-background-controller
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kyverno-cleanup-controller
  namespace: kyverno
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kyverno-cleanup-controller
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kyverno-reports-controller
  namespace: kyverno
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kyverno-reports-controller
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
