apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: flaresolverr
  namespace: media-video
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flaresolverr
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: jellyfin
  namespace: media-video
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jellyfin
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: jellyseerr
  namespace: media-video
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jellyseerr
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prowlarr
  namespace: media-video
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prowlarr
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: qbittorrent
  namespace: media-video
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qbittorrent
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: radarr
  namespace: media-video
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: radarr
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sonarr
  namespace: media-video
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sonarr
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
