apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trivy-operator
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsOnly
