deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  analytics:
    reporting_enabled: false
    usage_stats_url: ""
analytics:
  reporting_enabled: false
  usage_stats_url: ""
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi  # Adjust based on expected log volume
    storageClassName: "local-path"
    accessModes:
    - ReadWriteOnce
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
test:
  enabled: false
    
