deploymentMode: SingleBinary
loki:
  image:
    registry: reg.yiannis.io
    repository: proxy-dockerhub/grafana/loki
    tag: 3.6.10
    digest: sha256:f59e6aedfee6af2388d69962b178a35a23152573b4bf0937106746deb7146ec7
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  compactor:
    retention_enabled: true
    delete_request_store: filesystem
  limits_config:
    retention_period: 336h
  analytics:
    reporting_enabled: false
    usage_stats_url: ""
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: filesystem
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
analytics:
  reporting_enabled: false
  usage_stats_url: ""
gateway:
  image:
    registry: reg.yiannis.io
    repository: proxy-dockerhub/nginxinc/nginx-unprivileged
    tag: 1.29-alpine
    digest: sha256:601c823234c474696ded03d619e67f1e59538802731543099c691aea67e4a553
singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
    limits:
      memory: 1Gi
  persistence:
    enabled: true
    size: 20Gi
    storageClassName: "local-path"
    accessModes:
    - ReadWriteOnce
monitoring:
  serviceMonitor:
    enabled: true
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
lokiCanary:
  enabled: false
test:
  enabled: false
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
chunksCache:
  enabled: false
memcached:
  image:
    repository: reg.yiannis.io/proxy-dockerhub/library/memcached
    tag: 1.6.39-alpine@sha256:c8503d4491edd3110cc07d0465089d3a41cf1daf8645e71149e39a51835e92cd
memcachedExporter:
  image:
    repository: reg.yiannis.io/proxy-dockerhub/prom/memcached-exporter
    tag: v0.15.4@sha256:b6763ecb3c47f2408e0398518851b7f8c5fc46232b2649f8c78a321130c54266
resultsCache:
  allocatedMemory: 128
  allocatedCPU: 50m
sidecar:
  image:
    registry: reg.yiannis.io
    repository: proxy-dockerhub/kiwigrid/k8s-sidecar
    tag: 2.5.0
    sha: a6b3f707f883108376514489a94d6629109a327b2978e1d826cd104c4ca436df
