deploymentMode: Monolithic
loki:
  image:
    registry: reg.yiannis.io
    repository: proxy-dockerhub/grafana/loki
    tag: 3.7.3
    digest: sha256:70b9f699fc9bb868b62f1cfd4f787dfa50242f1fd92e6089787d5d7daea75fe8
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  compactor:
    retention_enabled: true
    delete_request_store: filesystem
  limits_config:
    retention_period: 336h
  analytics:
    reporting_enabled: false
    usage_stats_url: ""
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: filesystem
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
analytics:
  reporting_enabled: false
  usage_stats_url: ""
gateway:
  metrics:
    enabled: false
  image:
    registry: reg.yiannis.io
    repository: proxy-dockerhub/nginxinc/nginx-unprivileged
    tag: 1.31-alpine
    digest: sha256:592b23aa79a6e6c08ba4b20f1fff700e1328895705966722608e115d62e52d39
singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
    limits:
      memory: 1Gi
  persistence:
    enabled: true
    size: 20Gi
    storageClassName: "local-path"
    accessModes:
    - ReadWriteOnce
monitoring:
  serviceMonitor:
    enabled: true
lokiCanary:
  enabled: false
test:
  enabled: false
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
chunksCache:
  enabled: false
memcached:
  image:
    repository: reg.yiannis.io/proxy-dockerhub/library/memcached
    tag: 1.6.45-alpine@sha256:c29847751abb41f4c268c84fb3087fee05d4edcbda44409ccb5086e26148e8a7
memcachedExporter:
  image:
    repository: reg.yiannis.io/proxy-dockerhub/prom/memcached-exporter
    tag: v0.16.0@sha256:fa03aba2f2aa6f572bf56ba07dd2960c62433805427be0fddc8b21b8074c1728
resultsCache:
  allocatedMemory: 128
  allocatedCPU: 50m
sidecar:
  image:
    registry: reg.yiannis.io
    repository: proxy-dockerhub/kiwigrid/k8s-sidecar
    tag: 2.8.1
    sha: abb55b2165c60e8f97e473862c7a3123df6f67d44f592949577c29b8fb2df9d6
