firefly-db:
  storage:
    accessModes: ReadWriteOnce
    class: local-path
  nodeSelector:
    extraDiskNode: "true"

firefly-iii:
  nodeSelector:
    extraDiskNode: "true"

importer:
  fireflyiii:
    url: "http://localhost:8081"
