apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-db
  namespace: argocd
  labels:
    app: gitea-db
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    namespace: gitea
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/ipanagiotidis/homelab-gitops.git
    path: apps/gitea/kustomization-db
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - ServerSideApply=true
