updateStrategy:
  # -- Customize updateStrategy: RollingUpdate or OnDelete
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

providers:
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    allowEmptyServices: false
    publishedService:
      enabled: true

service:
  enabled: true
  type: LoadBalancer
  # -- Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
  annotations: 
    metallb.universe.tf/ip-allocated-from-pool: single-lb-pool
  spec:
    loadBalancerIP: "192.168.1.7"

securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

env:
  - name: TRAEFIK_ENTRYPOINTS_WEB_ADDRESS
    value: :80
  - name: TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS
    value: :443
  - name: TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO
    value: websecure