image:
  registry: reg.yiannis.io
  repository: proxy-dockerhub/library/traefik
  tag: v3.6.12@sha256:171c9c3565b29f6c133f1c1b43c5d4e5853415198e9e1078c001f8702ff66aec

versionOverride: v3.6.12

updateStrategy:
  # -- Customize updateStrategy: RollingUpdate or OnDelete
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

providers:
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    allowEmptyServices: false
    publishedService:
      enabled: true
  kubernetesGateway:
    enabled: true

gateway:
  enabled: false

gatewayClass:
  enabled: false

service:
  enabled: true
  type: LoadBalancer
  # -- Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
  annotations: 
    metallb.universe.tf/ip-allocated-from-pool: single-lb-pool
  spec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: "192.168.88.7"
  additionalServices:
    public:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/ip-allocated-from-pool: single-lb-pool
      spec:
        externalTrafficPolicy: Cluster
        loadBalancerIP: "192.168.88.6"

tlsStore:
  default:
    defaultCertificate:
      secretName: traefik-wildcard-tls

ingressClass:
  enabled: true
  isDefaultClass: true
  name: "traefik"

securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 25m
    memory: 128Mi

env:
  - name: TRAEFIK_ENTRYPOINTS_WEB_ADDRESS
    value: :80
  - name: TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS
    value: :443
  - name: TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO
    value: websecure
  - name: TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME
    value: https
  - name: TRAEFIK_ENTRYPOINTS_WEB_HTTP_MIDDLEWARES
    value: traefik-redirect-http-https@kubernetescrd,traefik-bouncer@kubernetescrd
  - name: TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_MIDDLEWARES
    value: traefik-redirect-http-https@kubernetescrd,traefik-bouncer@kubernetescrd

ports:
  webpublic:
    port: 8001
    expose:
      public: true
    exposedPort: 80
    protocol: TCP
  websecurepublic:
    port: 8444
    expose:
      public: true
    exposedPort: 443
    protocol: TCP

logs:
  general:
    format: "json"
  access:
    enabled: true
    format: "json"
    fields:
      headers: 
        defaultmode: keep

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`tf.yiannis.io`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    entryPoints: ["websecure"]
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Traefik
      gethomepage.dev/href: "https://tf.yiannis.io/dashboard/"
      gethomepage.dev/group: Ingress
      gethomepage.dev/icon: traefik.png
      gethomepage.dev/name: traefik
      gethomepage.dev/pod-selector: ""
      gethomepage.dev/widget.type: "traefik"
      gethomepage.dev/widget.url: "https://tf.yiannis.io"
    # middlewares:
    #   - name: authentik
    #     namespace: traefik
volumes:
  - name: crowdsec-bouncer-tls
    mountPath: /etc/traefik/crowdsec-certs/
    type: secret

experimental:
  plugins:
    bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.2"

additionalArguments:
  - "--experimental.plugins.bouncer.moduleName=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
  - "--experimental.plugins.bouncer.version=v1.4.2"
  - "--entrypoints.web.http.middlewares=traefik-redirect-http-https@kubernetescrd,traefik-bouncer@kubernetescrd"
  - "--entrypoints.websecure.http.middlewares=traefik-redirect-http-https@kubernetescrd,traefik-bouncer@kubernetescrd"
  - "--entrypoints.webpublic.http.redirections.entrypoint.to=websecurepublic"
  - "--entrypoints.webpublic.http.redirections.entrypoint.scheme=https"
  - "--entrypoints.webpublic.http.middlewares=traefik-redirect-http-https@kubernetescrd,traefik-bouncer@kubernetescrd"
  - "--entrypoints.websecurepublic.http.middlewares=traefik-redirect-http-https@kubernetescrd,traefik-bouncer@kubernetescrd"
  - "--providers.kubernetescrd"

metrics:
  prometheus:
    enabled: true
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    service:
      enabled: true
    serviceMonitor:
      enabled: true

# tracing:
#   otlp:
#     http:
#       endpoint: http://tempo.monitoring.svc.cluster.local:4318/v1/traces
