apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: bouncerr
  namespace: traefik
spec:
  plugin:
    bouncer:
      enabled: true
      crowdsecMode: live
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
      crowdsecLapiScheme: https
      crowdsecLapiTLSCertificateAuthorityFile: /etc/traefik/crowdsec-certs/ca.crt
      crowdsecLapiTLSCertificateBouncerFile: /etc/traefik/crowdsec-certs/tls.crt
      crowdsecLapiTLSCertificateBouncerKeyFile: /etc/traefik/crowdsec-certs/tls.key