apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: bouncer
  namespace: traefik
spec:
  plugin:
    bouncer:
      enabled: true
      logLevel: DEBUG
      crowdsecMode: none
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
      crowdsecLapiScheme: https
      crowdsecLapiTLSCertificateAuthorityFile: /etc/traefik/crowdsec-certs/ca.crt
      crowdsecLapiTLSCertificateBouncerFile: /etc/traefik/crowdsec-certs/tls.crt
      crowdsecLapiTLSCertificateBouncerKeyFile: /etc/traefik/crowdsec-certs/tls.key
      forwardedHeadersTrustedIPs:
        - 10.244.0.50/32
        - 10.244.2.101/32
      forwardedHeadersCustomName: Cf-Connecting-Ip
      # clientTrustedIPs:
      #   - 10.0.0.0/8
      #   - 172.16.0.0/12
      #   - 192.168.0.0/16