apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-service-certificate
spec:
  secretName: my-service-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - "yiannis.io"
  - "*.yiannis.io"