apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-wildcard-tls-certificate
spec:
  secretName: traefik-wildcard-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - "yiannis.io"
  - "*.yiannis.io"