apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./bouncer.yaml
  - ./certificate.yaml
  - ./cilium-network-policy.yaml
  - ./gatewayclass.yaml
  - ./middleware.yaml
  - ./jellyfin-tls.yaml
  - ./forwardauth.yaml
