apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: real-ip
  namespace: traefik
spec:
  plugin:
    real-ip:
      Proxy:
        - proxyHeadername: X-From-Cdn
          proxyHeadervalue: cf-foo
          realIP: Cf-Connecting-Ip
          OverwriteXFF: true # default: false, v1.0.2 or above