apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  instances: 1

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.11-1.1.0@sha256:94fd310260a3f05ce2d870e6da105c21cbadac9e25ac292c2a3c512b81444a04

  storage:
    size: 10Gi
    storageClass: truenas-cnpg

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  monitoring:
    enablePodMonitor: true

  postgresql:
    shared_preload_libraries:
      - vchord.so

  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
