apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-https
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: ArgoCD
    gethomepage.dev/href: "https://argocd.yiannis.io"
    gethomepage.dev/group: Platform
    gethomepage.dev/icon: argo-cd.png
    gethomepage.dev/name: argocd
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/widget.type: "argocd"
    gethomepage.dev/widget.url: "https://argocd.yiannis.io"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_ARGOCD_READONLY}}"
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`argocd.yiannis.io`)
    priority: 10
    services:
    - kind: Service
      name: argocd-server
      port: http
  - kind: Rule
    match: >-
      Host(`argocd.yiannis.io`) &&
      Header(`Content-Type`, `application/grpc`)
    priority: 11
    services:
    - kind: Service
      name: argocd-server
      port: http
      scheme: h2c