# Configure options applied to all pods
defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  # Configure the main controller
  prowlarr:

    # Configure the pod-specific securityContext
    pod:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault

    containers:
      # Configure the main application container
      prowlarr:
        image:
          # -- image repository
          repository: reg.yiannis.io/proxy-dockerhub/linuxserver/prowlarr
          # -- pinned to latest stable release tag: 2.3.5.5327-ls146
          digest: sha256:a89f252d6a22bd25af14a5380aec0adcc3c3af2e3282164f981680e6844070f3
        # Configure the container-specific securityContext
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - SETGID
              - SETUID
        # -- Configure the resource requests and/or limits for the Pod
        resources:
          requests:
          #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
          #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
          #   gpu.intel.com/i915: 1
            cpu: 25m
            memory: 256Mi
          limits:
          #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
          #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
          #  gpu.intel.com/i915: 1
            memory: 1024Mi


service:
  # Configure a service for the main application
  controller: prowlarr
  prowlarr:
    type: ClusterIP
    ports:
      http:
        port: 9696

ingress:
  # Configure an Ingress for the main application
  prowlarr:
    enabled: false
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Indexer manager
      gethomepage.dev/href: "https://prw.yiannis.io"
      gethomepage.dev/group: Media
      gethomepage.dev/icon: prowlarr.png
      gethomepage.dev/name: Prowlarr
      gethomepage.dev/pod-selector: ""
      gethomepage.dev/widget.type: "prowlarr"
      gethomepage.dev/widget.url: "http://prowlarr.media-video.svc.cluster.local:9696"
      gethomepage.dev/widget.key: '{{`{{HOMEPAGE_VAR_PROWLARR}}`}}'
    ingressClassName: "traefik"
    hosts:
      - host: "prw.yiannis.io"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: prowlarr
              port: http

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: truenas-apps
    accessMode: ReadWriteOnce
    size: 2Gi
    advancedMounts:
      prowlarr:
        prowlarr:
          - path: /config
