apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-homepage-var-argocd-readonly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: homepage-var-argocd-readonly
  data:
    - secretKey: key
      remoteRef:
        key: HOMEPAGE_VAR_ARGOCD_READONLY