apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-homepage-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: homepage-secrets
  data:
    - secretKey: argocd-key
      remoteRef:
        key: HOMEPAGE_VAR_ARGOCD_READONLY
    - secretKey: authentik-key
      remoteRef:
        key: HOMEPAGE_VAR_AUTHENTIK
    - secretKey: gitea-key
      remoteRef:
        key: HOMEPAGE_VAR_GITEA
    - secretKey: adguard-key
      remoteRef:
        key: HOMEPAGE_VAR_ADGUARD
    - secretKey: adguard-user
      remoteRef:
        key: HOMEPAGE_VAR_ADGUARD_USER
    - secretKey: adguard-server
      remoteRef:
        key: HOMEPAGE_VAR_ADGUARD_SERVER
    - secretKey: truenas-key
      remoteRef:
        key: HOMEPAGE_VAR_TRUENAS
    - secretKey: jf-key
      remoteRef:
        key: HOMEPAGE_VAR_JF
    - secretKey: jellyseerr-key
      remoteRef:
        key: HOMEPAGE_VAR_JELLYSEERR
    - secretKey: prowlarr-key
      remoteRef:
        key: HOMEPAGE_VAR_PROWLARR
    - secretKey: radarr-key
      remoteRef:
        key: HOMEPAGE_VAR_RADARR
    - secretKey: sonarr-key
      remoteRef:
        key: HOMEPAGE_VAR_SONARR
    - secretKey: immich-key
      remoteRef:
        key: HOMEPAGE_VAR_IMMICH
    - secretKey: qbittorrent-user
      remoteRef:
        key: HOMEPAGE_VAR_QBITTORRENT_USER
    - secretKey: qbittorrent-password
      remoteRef:
        key: HOMEPAGE_VAR_QBITTORRENT_PASSWORD
    - secretKey: paperless-token
      remoteRef:
        key: HOMEPAGE_VAR_PAPERLESS_TOKEN
