apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-homepage-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: homepage-secrets
  data:
    - secretKey: argocd-key
      remoteRef:
        key: HOMEPAGE_VAR_ARGOCD_READONLY
    - secretKey: authentik-key
      remoteRef:
        key: HOMEPAGE_VAR_AUTHENTIK
    - secretKey: gitea-key
      remoteRef:
        key: HOMEPAGE_VAR_GITEA