global:  
  hostAliases:
    - ip: 192.168.88.7
      hostnames:
      - "argocd.yiannis.io"
      - "authentik.yiannis.io"
      - "gitea.yiannis.io"

redis-cluster:
  enabled: false
postgresql:
  enabled: true
  primary:
    nodeSelector:
      extraDiskNode: "true"
  
postgresql-ha:
  enabled: false

persistence:
  enabled: true
  storageClass: local-path

nodeSelector: 
  extraDiskNode: "true" 

gitea:
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
    server:
      ROOT_URL: https://gitea.yiannis.io/
  oauth:
    - name: "authentik"
      provider: "openidConnect"
      existingSecret: gitea-authentik-secret
      autoDiscoverUrl: "http://authentik.yiannis.io/application/o/gitea-slug/.well-known/openid-configuration"
      iconUrl: "https://goauthentik.io/img/icon.png"
      scopes: "email profile"

deployment:
  env:
    - name: ENABLE_PASSWORD_SIGNIN_FORM
      value: "false"
    - name: ENABLE_BASIC_AUTHENTICATION
      value: "false"
    - name: DISABLE_REGISTRATION
      value: "true"
    - name: REQUIRE_EXTERNAL_REGISTRATION_PASSWORD
      value: "true"
    - name: ENABLE_CAPTCHA
      value: "true"
    - name: REQUIRE_EXTERNAL_REGISTRATION_CAPTCHA
      value: "true"

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: gitea.yiannis.io
      paths:
        - path: "/"
          pathType: Prefix