redis-cluster:
  enabled: false
postgresql:
  enabled: true
  primary:
    nodeSelector:
      extraDiskNode: "true"
  
postgresql-ha:
  enabled: false

persistence:
  enabled: true
  storageClass: local-path

nodeSelector: 
  extraDiskNode: "true" 

gitea:
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: gitea.yiannis.io
      paths:
        - path: "/"
          pathType: Prefix

gitea:
  oauth:
    - name: "authentik"
      provider: "openidConnect"
      existingSecret: gitea-authentik-secret
      autoDiscoveryUrl: "http://authentik.yiannis.io/application/o/gitea-slug/.well-known/openid-configuration"
      iconUrl: "https://goauthentik.io/img/icon.png"
      scopes: "email profile"