image:
  tag: 1.23.4

redis-cluster:
  enabled: false
postgresql:
  enabled: true
  primary:
    nodeSelector:
      extraDiskNode: "true"
  
postgresql-ha:
  enabled: false

persistence:
  enabled: true
  storageClass: local-path

nodeSelector: 
  extraDiskNode: "true" 

gitea:
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
    server:
      ROOT_URL: https://gitea.yiannis.io/
    service:
      DISABLE_REGISTRATION: "true"
      ENABLE_BASIC_AUTHENTICATION: "false"
      ENABLE_PASSWORD_SIGNIN_FORM: "false"
      ENABLE_CAPTCHA: "true"
      REQUIRE_EXTERNAL_REGISTRATION_CAPTCHA: "true"
      REQUIRE_CAPTCHA_FOR_LOGIN: "true"
    oauth2_client:
      ENABLE_AUTO_REGISTRATION: "true"
  oauth:
    - name: "authentik"
      provider: "openidConnect"
      existingSecret: gitea-authentik-secret
      autoDiscoverUrl: "http://authz.yiannis.io/application/o/gitea-slug/.well-known/openid-configuration"
      iconUrl: "https://goauthentik.io/img/icon.png"
      scopes: "email profile"

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: gitea.yiannis.io
      paths:
        - path: "/"
          pathType: Prefix