apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ../base

patches:
- path: ./patches/argocd-cmd-params-cm.yaml
- path: ./patches/argocd-cm.yaml
- path: ./patches/argocd-rbac-cm.yaml
- path: ./patches/argocd-dex-service.yaml