apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - disallow-latest-tag.yaml
  - require-drop-all-capabilities-audit.yaml
  - require-harbor-registry-audit.yaml
  - require-harbor-registry-enforce.yaml
  - require-labels.yaml
  - require-runtime-hardening-audit.yaml
