# Configure options applied to all pods
defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  # Configure the main controller
  jellyseerr:

    # Configure the pod-specific securityContext
    pod:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      # Configure the main application container
      jellyseerr:
        image:
          # -- image repository
          repository: reg.yiannis.io/proxy-ghcr/seerr-team/seerr
          # -- pinned to latest stable release tag: v3.1.0
          digest: sha256:b35ba0461c4a1033d117ac1e5968fd4cbe777899e4cbfbdeaf3d10a42a0eb7e9
        # Configure the container-specific securityContext
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
        # -- Configure the resource requests and/or limits for the Pod
        resources:
          requests:
          #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
          #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
          #   gpu.intel.com/i915: 1
            cpu: 200m
            memory: 256Mi
          limits:
          #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
          #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
          #  gpu.intel.com/i915: 1
            memory: 4096Mi


service:
  # Configure a service for the main application
  controller: jellyseerr
  jellyseerr:
    type: ClusterIP
    ports:
      http:
        port: 5055

ingress:
  # Configure an Ingress for the main application
  jellyseerr:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Request management
      gethomepage.dev/href: "https://demandeur.yiannis.io"
      gethomepage.dev/group: Media
      gethomepage.dev/icon: jellyseerr.png
      gethomepage.dev/name: Jellyseerr
      gethomepage.dev/pod-selector: ""
      gethomepage.dev/widget.type: "jellyseerr"
      gethomepage.dev/widget.url: "http://jellyseerr.media-video.svc.cluster.local:5055"
      gethomepage.dev/widget.key: '{{`{{HOMEPAGE_VAR_JELLYSEERR}}`}}'
    ingressClassName: "traefik"
    hosts:
      - host: "demandeur.yiannis.io"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: jellyseerr
              port: http

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: truenas-apps
    accessMode: ReadWriteOnce
    size: 2Gi
    advancedMounts:
      jellyseerr:
        jellyseerr:
          - path: /app/config
