apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-harbor
  namespace: harbor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: harbor-secrets
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: HARBOR_ADMIN_PASSWORD
    - secretKey: secretKey
      remoteRef:
        key: HARBOR_SECRET_KEY
