apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-harbor
  namespace: harbor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: harbor-secrets
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: HARBOR_ADMIN_PASSWORD
    - secretKey: secretKey
      remoteRef:
        key: HARBOR_SECRET_KEY
    - secretKey: secret
      remoteRef:
        key: HARBOR_CORE_SECRET
    - secretKey: CSRF_KEY
      remoteRef:
        key: HARBOR_CSRF_KEY
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: HARBOR_JOBSERVICE_SECRET
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        key: HARBOR_REGISTRY_HTTP_SECRET
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        key: HARBOR_REGISTRY_PASSWORD
    - secretKey: REGISTRY_HTPASSWD
      remoteRef:
        key: HARBOR_REGISTRY_HTPASSWD
    - secretKey: tls.key
      remoteRef:
        key: HARBOR_TOKEN_TLS_KEY
    - secretKey: tls.crt
      remoteRef:
        key: HARBOR_TOKEN_TLS_CERT
