apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-harbor
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: harbor-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: HARBOR_ADMIN_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HARBOR_ADMIN_PASSWORD
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: secretKey
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HARBOR_SECRET_KEY
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: secret
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HARBOR_CORE_SECRET
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: CSRF_KEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HARBOR_CSRF_KEY
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: JOBSERVICE_SECRET
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HARBOR_JOBSERVICE_SECRET
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: REGISTRY_HTTP_SECRET
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HARBOR_REGISTRY_HTTP_SECRET
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: REGISTRY_PASSWD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HARBOR_REGISTRY_PASSWORD
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: REGISTRY_HTPASSWD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HARBOR_REGISTRY_HTPASSWD
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: tls.key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HARBOR_TOKEN_TLS_KEY
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: tls.crt
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HARBOR_TOKEN_TLS_CERT
      metadataPolicy: None
      nullBytePolicy: Ignore
