apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ./cilium-network-policy.yaml

images:
- name: quay.io/metallb/controller
  newName: reg.yiannis.io/proxy-quay/metallb/controller
  digest: sha256:6698ccc54c380913816ed1fd0758637ec87dd79da419c4ab170a2c26c158ab89
- name: quay.io/metallb/speaker
  newName: reg.yiannis.io/proxy-quay/metallb/speaker
  digest: sha256:c6a5b25b2e1fba610a57b2db4bb8141d7c133569d561a8cc29e38ca5113efbc4
