defaultPodOptions:
  automountServiceAccountToken: true
  enableServiceLinks: false

controllers:
  homepage:
    strategy: RollingUpdate
    revisionHistoryLimit: 3
    serviceAccount:
      identifier: default
    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    containers:
      homepage:
        image:
          repository: reg.yiannis.io/proxy-ghcr/gethomepage/homepage
          tag: v1.12.3
          digest: sha256:cc84f2f5eb3c7734353701ccbaa24ed02dacb0d119114e50e4251e2005f3990a
        env:
          HOMEPAGE_ALLOWED_HOSTS: home.yiannis.io
          HOMEPAGE_VAR_ARGOCD_READONLY:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: argocd-key
          HOMEPAGE_VAR_AUTHENTIK:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: authentik-key
          HOMEPAGE_VAR_GITEA:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: gitea-key
          HOMEPAGE_VAR_ADGUARD:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: adguard-key
          HOMEPAGE_VAR_ADGUARD_SERVER:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: adguard-server
          HOMEPAGE_VAR_ADGUARD_USER:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: adguard-user
          HOMEPAGE_VAR_TRUENAS:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: truenas-key
          HOMEPAGE_VAR_JF:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: jf-key
          HOMEPAGE_VAR_JELLYSEERR:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: jellyseerr-key
          HOMEPAGE_VAR_PROWLARR:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: prowlarr-key
          HOMEPAGE_VAR_RADARR:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: radarr-key
          HOMEPAGE_VAR_SONARR:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: sonarr-key
          HOMEPAGE_VAR_IMMICH:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: immich-key
          HOMEPAGE_VAR_QBITTORRENT_USER:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: qbittorrent-user
          HOMEPAGE_VAR_QBITTORRENT_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: qbittorrent-password
          HOMEPAGE_VAR_PAPERLESS_TOKEN:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: paperless-token
          HOMEPAGE_VAR_SPEEDTEST:
            valueFrom:
              secretKeyRef:
                name: homepage-secrets
                key: speedtest-key
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 500m
            memory: 200Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 3000
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 3000
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          startup:
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 3000
              periodSeconds: 5
              timeoutSeconds: 1
              failureThreshold: 30

serviceAccount:
  default:
    enabled: true
    forceRename: homepage

rbac:
  roles:
    homepage:
      enabled: true
      type: ClusterRole
      forceRename: homepage
      rules:
        - apiGroups:
            - ""
          resources:
            - namespaces
            - pods
            - nodes
          verbs:
            - get
            - list
        - apiGroups:
            - extensions
            - networking.k8s.io
          resources:
            - ingresses
          verbs:
            - get
            - list
        - apiGroups:
            - traefik.containo.us
            - traefik.io
          resources:
            - ingressroutes
          verbs:
            - get
            - list
        - apiGroups:
            - gateway.networking.k8s.io
          resources:
            - httproutes
            - gateways
          verbs:
            - get
            - list
        - apiGroups:
            - metrics.k8s.io
          resources:
            - nodes
            - pods
          verbs:
            - get
            - list
        - apiGroups:
            - apiextensions.k8s.io
          resources:
            - customresourcedefinitions/status
          verbs:
            - get
  bindings:
    homepage:
      enabled: true
      type: ClusterRoleBinding
      forceRename: homepage
      roleRef:
        identifier: homepage
      subjects:
        - identifier: default

configMaps:
  homepage:
    enabled: true
    forceRename: homepage
    data:
      bookmarks.yaml: ""
      docker.yaml: ""
      kubernetes.yaml: |
        ingress: true
        mode: cluster
        traefik: true
        gateway: true
      services.yaml: |
        - Monitoring:
          - prometheus:
              description: Metrics and targets
              href: https://gfn.yiannis.io
              icon: prometheus.png
              name: prometheus
              widget:
                type: prometheus
                url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        - Infrastructure:
          - adguard:
              description: Adguard
              href: '{{`{{HOMEPAGE_VAR_ADGUARD_SERVER}}`}}'
              icon: adguard-home.png
              name: adguard
              widget:
                type: adguard
                url: '{{`{{HOMEPAGE_VAR_ADGUARD_SERVER}}`}}'
                username: '{{`{{HOMEPAGE_VAR_ADGUARD_USER}}`}}'
                password: '{{`{{HOMEPAGE_VAR_ADGUARD}}`}}'
          - truenas:
              description: NAS and storage status
              href: https://truenas.yiannis.io
              icon: truenas.png
              name: truenas
              widget:
                type: truenas
                url: https://truenas.yiannis.io
                key: '{{`{{HOMEPAGE_VAR_TRUENAS}}`}}'
                version: 2
      settings.yaml: |
        title: Homepage Private
        headerStyle: boxed
        layout:
          Platform:
          Monitoring:
          Services:
          Infrastructure:
          Media:
      widgets.yaml: |
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: k8s-homelab
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true

service:
  homepage:
    controller: homepage
    primary: true
    ports:
      http:
        port: 3000

ingress:
  homepage:
    enabled: false

persistence:
  base-config:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /app/config

  homepage-config:
    enabled: true
    type: configMap
    identifier: homepage
    advancedMounts:
      homepage:
        homepage:
          - path: /app/config/bookmarks.yaml
            subPath: bookmarks.yaml
            readOnly: true
          - path: /app/config/docker.yaml
            subPath: docker.yaml
            readOnly: true
          - path: /app/config/kubernetes.yaml
            subPath: kubernetes.yaml
            readOnly: true
          - path: /app/config/services.yaml
            subPath: services.yaml
            readOnly: true
          - path: /app/config/settings.yaml
            subPath: settings.yaml
            readOnly: true
          - path: /app/config/widgets.yaml
            subPath: widgets.yaml
            readOnly: true

  logs:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /app/config/logs

  tmp:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /tmp
