# Configure options applied to all pods
defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  # Configure the main controller
  radarr:

    # Configure the pod-specific securityContext
    pod:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      # Configure the main application container
      radarr:
        image:
          # -- image repository
          repository: reg.yiannis.io/proxy-dockerhub/linuxserver/radarr
          # -- pinned to latest stable release tag: 6.1.1.10360-ls297
          digest: sha256:581f159c2b67436863cb4da30e158ef6f6b8878472abbba79ee5d5f7e6b7d28d
        # Configure the container-specific securityContext
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
        # -- Configure the resource requests and/or limits for the Pod
        resources:
          requests:
          #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
          #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
          #   gpu.intel.com/i915: 1
            cpu: 10m
            memory: 128Mi
          limits:
          #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
          #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
          #  gpu.intel.com/i915: 1
            memory: 4096Mi


service:
  # Configure a service for the main application
  controller: radarr
  radarr:
    type: ClusterIP
    ports:
      http:
        port: 7878

ingress:
  # Configure an Ingress for the main application
  radarr:
    enabled: false
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Movie management
      gethomepage.dev/href: "https://rdr.yiannis.io"
      gethomepage.dev/group: Media
      gethomepage.dev/icon: radarr.png
      gethomepage.dev/name: Radarr
      gethomepage.dev/pod-selector: ""
      gethomepage.dev/widget.type: "radarr"
      gethomepage.dev/widget.url: "http://radarr.media-video.svc.cluster.local:7878"
      gethomepage.dev/widget.key: '{{`{{HOMEPAGE_VAR_RADARR}}`}}'
    ingressClassName: "traefik"
    hosts:
      - host: "rdr.yiannis.io"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: radarr
              port: http

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: truenas-apps
    accessMode: ReadWriteOnce
    size: 2Gi
    globalMounts:
      - path: /config

  media:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: media-video
    globalMounts:
      - path: /data
