apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-crowdsec-lapi-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: crowdsec-lapi-secrets
  data:
    - secretKey: csLapiSecret
      remoteRef:
        key: CROWDSEC_LAPI_SECRET
    - secretKey: registrationToken
      remoteRef:
        key: CROWDSEC_REGISTRATION_TOKEN
