apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-ngx-database
  namespace: paperless-ngx
spec:
  instances: 1

  storage:
    size: 5Gi
    storageClass: truenas-cnpg

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  bootstrap:
    initdb:
      database: paperless
      owner: paperless
