apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-paperless-ngx
  namespace: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: paperless-ngx-secret
  data:
    - secretKey: secret-key
      remoteRef:
        key: PAPERLESS_SECRET_KEY
    - secretKey: admin-user
      remoteRef:
        key: PAPERLESS_ADMIN_USER
    - secretKey: admin-password
      remoteRef:
        key: PAPERLESS_ADMIN_PASSWORD
