apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-paperless-ngx
  namespace: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: paperless-ngx-secret
    template:
      engineVersion: v2
      data:
        socialaccount-providers: |
          {
            "openid_connect": {
              "OAUTH_PKCE_ENABLED": true,
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "Authentik",
                  "client_id": "{{ .oidc_client_id }}",
                  "secret": "{{ .oidc_client_secret }}",
                  "settings": {
                    "server_url": "{{ .oidc_issuer }}",
                    "fetch_userinfo": true
                  }
                }
              ],
              "SCOPE": ["openid", "profile", "email", "groups"]
            }
          }
        oidc_logout_redirect_url: "{{ .oidc_logout_redirect_url }}"
  data:
    - secretKey: secret-key
      remoteRef:
        key: PAPERLESS_SECRET_KEY
    - secretKey: admin-user
      remoteRef:
        key: PAPERLESS_ADMIN_USER
    - secretKey: admin-password
      remoteRef:
        key: PAPERLESS_ADMIN_PASSWORD
    - secretKey: oidc_client_id
      remoteRef:
        key: PAPERLESS_OIDC_CLIENT_ID
    - secretKey: oidc_client_secret
      remoteRef:
        key: PAPERLESS_OIDC_CLIENT_SECRET
    - secretKey: oidc_issuer
      remoteRef:
        key: PAPERLESS_OIDC_ISSUER
    - secretKey: oidc_logout_redirect_url
      remoteRef:
        key: PAPERLESS_OIDC_LOGOUT_REDIRECT_URL
