apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-database
  namespace: harbor
spec:
  instances: 1

  imageName: reg.yiannis.io/proxy-ghcr/cloudnative-pg/postgresql:18.3-system-trixie@sha256:83eed1b1712edd8d881e5cf1b989519b8863f123aa9e2232fffaef5afa20a0c3

  storage:
    size: 8Gi
    storageClass: truenas-cnpg

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: registry
      owner: harbor
      secret:
        name: harbor-cnpg-app
