apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-harbor-cnpg-app
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: harbor-cnpg-app
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/basic-auth
      data:
        username: harbor
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: HARBOR_POSTGRES_PASSWORD
      metadataPolicy: None
      nullBytePolicy: Ignore
