apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-harbor-cnpg-app
  namespace: harbor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: harbor-cnpg-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: harbor
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: HARBOR_POSTGRES_PASSWORD
