apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-database
  namespace: authentik
spec:
  instances: 1

  imageName: reg.yiannis.io/proxy-ghcr/cloudnative-pg/postgresql:18.1-system-trixie@sha256:51bc94428be3df3e234447278e33803544a93d27a57a4b6af737f218d6472d12

  storage:
    size: 8Gi
    storageClass: truenas-cnpg

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-cnpg-app
