# for raw logs format: json or cri (docker|containerd)
container_runtime: containerd
agent:
  # Specify each pod whose logs you want to process
  acquisition:
    # The namespace where the pod is located
    - namespace: traefik
      # The pod name
      podName: traefik-*
      # as in crowdsec configuration, we need to specify the program name to find a matching parser
      program: traefik
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
  nodeSelector:
    extraDiskNode: "true"
    kubernetes.io/hostname: k8s-node-5
lapi:
  env:
    # To enroll the Security Engine to the console
    - name: ENROLL_KEY
      value: ""
    - name: ENROLL_INSTANCE_NAME
      value: "homelab-k8s-cluster"
    - name: ENROLL_TAGS
      value: "homelab crowdsec kubernetes"
  nodeSelector:
    extraDiskNode: "true"
    kubernetes.io/hostname: k8s-node-5


