# for raw logs format: json or cri (docker|containerd)
container_runtime: containerd
agent:
  # Specify each pod whose logs you want to process
  acquisition:
    # The namespace where the pod is located
    - namespace: traefik
      # The pod name
      podName: traefik-*
      # as in crowdsec configuration, we need to specify the program name to find a matching parser
      program: traefik
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
    - name: DISABLE_ONLINE_API
      value: "false"
    - name: DISABLE_PARSERS
      value: "crowdsecurity/whitelists"
    - name: LAPI_URL
      value: "https://crowdsec-service.crowdsec.svc.cluster.local:8080"
lapi:
  env:
    # To enroll the Security Engine to the console
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-enroll-secret
          key: key
    - name: ENROLL_INSTANCE_NAME
      value: "homelab-k8s-cluster"
    - name: ENROLL_TAGS
      value: "homelab crowdsec kubernetes"
    - name: DISABLE_ONLINE_API
      value: "false"
    - name: DISABLE_PARSERS
      value: "crowdsecurity/whitelists"
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
  nodeSelector:
    extraDiskNode: "true"
    kubernetes.io/hostname: k8s-node-5


