loki:
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
  singleBinary:
    replicas: 1
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
  test:
    enabled: true
