image:
  tag: v2.4.1

immich:
  metrics:
    enabled: true

  persistence:
    library:
      existingClaim: immich-library

  server:
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Immich
          gethomepage.dev/href: "https://photos.yiannis.io"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: immich.png
          gethomepage.dev/name: Immich
          gethomepage.dev/pod-selector: ""
        hosts:
          - host: photos.yiannis.io
            paths:
              - path: /
                pathType: Prefix

externalDatabase:
  enabled: true
  type: postgresql
  host: immich-database-rw
  port: 5432
  username: immich
  database: immich
  existingSecret:
    enabled: true
    secretName: immich-database-app
    key: password

valkey:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: truenas-apps
      size: 2Gi
