---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: single-lb-pool
spec:
  addresses:
  - 192.168.88.6-192.168.88.7
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: single-lb-l2ad
spec:
  ipAddressPools:
  - single-lb-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: second-lb-pool
spec:
  addresses:
  - 192.168.88.8,192.168.88.4
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: second-lb-l2ad
spec:
  ipAddressPools:
  - second-lb-pool