---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: single-lb-pool
spec:
  addresses:
  - 192.168.1.6-192.168.1.7
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: single-lb-l2ad
spec:
  ipAddressPools:
  - single-lb-pool